#!/bin/bash

# Install packages listed in 'data/aur-packages.list'
function aurpackages
{
    show_info 'Installing...'
    show_warning 'Requires root privileges'
    sudo pacman -Sy
    while read F ; do
        yay -S --needed --noconfirm "$F"
    done < $AURPKGS

    show_success 'Done.'

    whiptail --title "Finished" --msgbox "All AUR packages installed." 8 78
    main
}
